export const COMMAND_CATEGORIES = [
  'version',
  'read_only',
  'typecheck',
  'lint',
  'format',
  'test',
  'build',
  'script',
  'dependency_install',
] as const;

export type CommandCategory = (typeof COMMAND_CATEGORIES)[number];

export interface ProgramRule {
  category: CommandCategory;
  subcommands?: Readonly<Record<string, CommandCategory>>;
  requiresSubcommand?: boolean;
}

export const DENIED_PROGRAMS: readonly string[] = [
  'sh',
  'bash',
  'zsh',
  'dash',
  'ksh',
  'fish',
  'csh',
  'cmd',
  'powershell',
  'pwsh',
  'eval',
  'exec',
  'source',
  'curl',
  'wget',
  'nc',
  'ncat',
  'netcat',
  'telnet',
  'ssh',
  'scp',
  'sftp',
  'rsync',
  'ftp',
  'dig',
  'nslookup',
  'ping',
  'traceroute',
  'iptables',
  'sudo',
  'su',
  'doas',
  'chmod',
  'chown',
  'chroot',
  'mount',
  'umount',
  'systemctl',
  'service',
  'kill',
  'killall',
  'pkill',
  'reboot',
  'shutdown',
  'docker',
  'podman',
  'kubectl',
  'helm',
  'terraform',
  'aws',
  'gcloud',
  'az',
  'gh',
  'glab',
  'rm',
  'mv',
  'cp',
  'dd',
  'ln',
  'mkfifo',
  'env',
  'printenv',
  'set',
  'export',
  'crontab',
  'at',
  'nohup',
  'screen',
  'tmux',
  'xargs',
  'find',
  'perl',
  'ruby',
  'php',
  'lua',
  'openssl',
  'base64',
  'gpg',
];

export const CODE_STRING_FLAGS: readonly string[] = ['-c', '-e', '--eval', '--exec', '--command'];

export const GLOBALLY_DENIED_FLAGS: readonly string[] = [
  '--registry',
  '--userconfig',
  '--globalconfig',
  '--prefix',
  '--global',
  '--unsafe-perm',
  '--allow-root',
  '--no-sandbox',
  '--script-shell',
  '--foreground-scripts',
  '--ignore-scripts=false',
  '--upload-token',
  '--token',
  '--auth',
  '--proxy',
  '--https-proxy',
  '--cafile',
  '--exec',
  '--eval',
];

export const IGNORE_SCRIPTS_FLAG = '--ignore-scripts';

export const DEPENDENCY_SUBCOMMANDS: readonly string[] = [
  'install',
  'i',
  'add',
  'remove',
  'uninstall',
  'update',
  'upgrade',
  'ci',
  'link',
  'dedupe',
  'prune',
  'rebuild',
];

export const PROGRAM_RULES: Readonly<Record<string, ProgramRule>> = {
  git: {
    category: 'read_only',
    requiresSubcommand: true,
    subcommands: {
      status: 'read_only',
      diff: 'read_only',
      log: 'read_only',
      show: 'read_only',
      'ls-files': 'read_only',
      'rev-parse': 'read_only',
      'symbolic-ref': 'read_only',
      blame: 'read_only',
      shortlog: 'read_only',
    },
  },
  node: { category: 'version' },
  npm: { category: 'script', requiresSubcommand: true },
  pnpm: { category: 'script', requiresSubcommand: true },
  yarn: { category: 'script', requiresSubcommand: true },
  npx: { category: 'script', requiresSubcommand: true },
  tsc: { category: 'typecheck' },
  eslint: { category: 'lint' },
  prettier: { category: 'format' },
  vitest: { category: 'test' },
  jest: { category: 'test' },
  mocha: { category: 'test' },
  playwright: { category: 'test' },
  pytest: { category: 'test' },
  ruff: { category: 'lint' },
  mypy: { category: 'typecheck' },
  go: {
    category: 'read_only',
    requiresSubcommand: true,
    subcommands: { build: 'build', test: 'test', vet: 'lint', fmt: 'format', version: 'version' },
  },
  cargo: {
    category: 'read_only',
    requiresSubcommand: true,
    subcommands: {
      build: 'build',
      test: 'test',
      check: 'typecheck',
      clippy: 'lint',
      fmt: 'format',
    },
  },
};

export const PACKAGE_MANAGERS: readonly string[] = ['npm', 'pnpm', 'yarn', 'npx'];

export const SCRIPT_NAME_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9:_.-]{0,63}$/;
